GET http://localhost:3000/date

###

GET https://tuoitre.vn/thoi-su/trang-1.htm

###

GET https://tuoitre.vn/cong-bo-so-dien-thoai-de-xu-ly-chuan-hoa-thong-tin-thue-bao-di-dong-20230318182559955.htm

###

GET https://tuoitre.vn/quoc-hoi-my-chia-re-vu-cam-tiktok-20230301121811715.htm

###

GET https://tuoitre.vn/thanh-thep-roi-lam-3-nguoi-di-vien-cong-truong-lap-luoi-an-toan-nhung-ho-hung-nhu-khong-20230314224150754.htm

###

GET https://tuoitre.vn/rrr-va-cuoc-giai-phong-am-nhac-20230319100823032.htm

###

GET https://tuoitre.vn/lo-sat-lo-hang-chuc-nguoi-dan-phan-ung-xang-cap-nao-vet-cat-2018011614303278.htm

###

GET https://tuoitre.vn/chuyen-nghiep-doi-tien-nha-bao-hiem-45554.htm

###

# TN feed
GET https://thanhnien.vn/timelinelist/1854/1.htm

###

# 2023, multiple authors, quote, highlight
GET https://thanhnien.vn/ngan-ngua-tham-nhung-tang-hieu-qua-giai-quyet-an-hanh-chinh-185230320225820281.htm

###

# 2020, video
GET https://thanhnien.vn/bo-cong-an-rut-de-xuat-thoi-han-bang-lai-xe-con-5-nam-185988475.htm

###

# 2018, photo, video, highlight
GET https://thanhnien.vn/trang-dem-di-dan-chay-lu-185874066.htm

###

# 2015, photo
GET https://thanhnien.vn/hon-2511-ti-dong-boi-thuong-giai-phong-mat-bang-2-du-an-o-dung-quat-185445866.htm

###

# 2009
GET https://thanhnien.vn/ha-noi-chay-lien-kho-hang-thiet-hai-hang-tram-ti-dong-185359224.htm

###

# 2004
GET https://thanhnien.vn/da-den-luc-rut-kinh-nghiem-thuc-su-185418775.htm
